- name: Install NodeJS 20
  ansible.builtin.dnf:
    name: '@nodejs:20'
    state: present

- name: Add roboshop application user
  ansible.builtin.user:
    name: roboshop

- name: Remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
    dest: /app
    remote_src: yes

- name: Install packages based on package.json.
  community.general.npm:
    path: /app

- name: Copy user service file
  ansible.builtin.copy:
    src: user.service
    dest: /etc/systemd/system/user.service

- name: Start User service
  ansible.builtin.systemd_service:
    state: restarted
    name: user
    enabled: true
    daemon_reload: true
